# Generated by Django 5.1.6 on 2025-03-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletoken',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
